#!/bin/bash

echo 'Database initialization'
echo ' + parsing CardData.inc'
# echo '-- autogenerated file' > CardData.sql # I don't know why I dont get the trailing newline here
sed -f compileCardDataPass1.sed ../include/common/CardData.inc > CardData.sql;
sed -e ":a;\$!N;/;/"'!'"ba;s/\\n//g" -i CardData.sql;
echo 'CREATE TEMPORARY VIEW ENUM_VALUES AS' >> CardData.sql;
sed -f compileCardDataPass2.sed ../include/common/CardData.inc > CardData.tmp;
sed -f compileCardDataPass3.sed CardData.tmp >> CardData.sql;

echo ' + creating db files'
rm -f ../resources/server/database.db
rm -f ../resources/client/database.db
sqlite3 :memory: ".read initdatabase.sql"
